### PR TITLE
Add an option to use regular expressions for keywords

### PR DESCRIPTION
**Pull request by ouuan**
It's useful for some complicated syntax.

It's optional and disabled by default so that it's compatible with old voice packages.

### CODE REVIEW

**Comment by SaekiRaku** [comment]
Hi, thanks for your PR! The property of `regexp`changes the whole keywords behaviour, it will cause some duplicated configuration if someone wants to use both `regexp` and the regular way. I'm thinking it may be better to use `regexp` as keywords too, like this:

```
{
    "keywords": [  "...", "..."  ],
    "regexp": [ "...", "..." ]
}
```

Could you please change this?

**Comment by ouuan** [comment]
> Hi, thanks for your PR! The property of `regexp`changes the whole keywords behaviour, it will cause some duplicated configuration if someone wants to use both `regexp` and the regular way. I'm thinking it may be better to use `regexp` as keywords too, like this:
> 
> ```
> {
>     "keywords": [  "...", "..."  ],
>     "regexp": [ "...", "..." ]
> }
> ```
> 
> Could you please change this?

OK.

**Comment by ouuan** [comment]
I found that if there are more matches, there will be more candidates, is this expected? Or was the keywords expected to be unique so that only one keyword is matched each time?

**Comment by SaekiRaku** [comment]
It seems like a BUG, but on other hands, the more candidates mean the more keywords were matched. And the right voice will have a greater probability to be played. It's harmless for users, so we can leave it be and see what is going. If it leads to a new BUG, we can fix it later.

**Comment by ouuan** [comment]
Now the margin is incorrect if there are only regexps :thinking:

**Comment by SaekiRaku** [comment]
Thnks for your contributes!

**Comment by SaekiRaku** [comment]
A new version has released to VSCode Marketplace. Thanks again!

**Pull request merged**
